In [1]:
import pandas as pd
import csv

In [45]:
Data = pd.read_csv('./weather/新北市資料/466880-2013-01-02.csv',skiprows=1)
date = '2013-01-02'
Data['Date'] = date
Data

,ObsTime,StnPres,SeaPres,Temperature,Td dew point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,SunShine,GloblRad,Visb,UVI,Cloud Amount,Date
0,1,1017.9,1019.2,14.5,12.5,88,2.0,30,4.3,90,T,1.0,...,0.00,...,...,...,2013-01-02
1,2,1017.8,1019.1,14.8,12.6,87,1.1,30,4.7,30,T,0.5,...,0.00,16.0,...,10.0,2013-01-02
2,3,1017.3,1018.6,14.9,12.5,86,1.1,20,2.8,10,0.0,0.0,...,0.00,...,...,...,2013-01-02
3,4,1017.2,1018.5,15.1,12.7,86,0.7,350,2.7,350,0.0,0.0,...,0.00,...,...,...,2013-01-02
4,5,1017.2,1018.5,14.5,12.6,88,0.1,0,1.8,340,0.0,0.0,...,0.00,15.0,...,10.0,2013-01-02
5,6,1018.1,1019.4,14.4,12.5,88,1.2,200,2.5,200,0.0,0.0,0.0,0.00,...,...,...,2013-01-02
6,7,1018.7,1020.0,14.4,12.5,88,0.9,190,2.7,210,0.0,0.0,0.0,0.00,...,...,...,2013-01-02
7,8,1019.3,1020.6,14.9,12.9,88,0.8,170,2.4,210,0.0,0.0,0.0,0.00,15.0,...,9.0,2013-01-02
8,9,1019.7,1021.0,16.2,13.4,83,0.1,0,1.9,210,0.0,0.0,0.1,0.51,15.0,...,9.0,2013-01-02
9,10,1020.2,1021.5,17.3,14.2,82,0.2,0,1.6,300,T,0.5,0.0,0.62,...,...,...,2013-01-02
10,11,1019.6,1020.9,18.9,14.8,77,0.8,250,2.3,260,0.0,0.0,0.4,1.51,13.0,...,8.0,2013-01-02
11,12,1019.4,1020.7,19.5,14.2,71,1.6,210,3.5,230,0.0,0.0,0.2,1.05,...,...,...,2013-01-02
12,13,1018.8,1020.1,19.3,14.1,72,0.8,200,2.5,200,0.0,0.0,0.0,0.30,...,...,...,2013-01-02
13,14,1018.2,1019.5,20.0,14.3,70,1.8,240,3.3,210,0.0,0.0,0.0,0.60,10.0,...,7.0,2013-01-02
14,15,1018.2,1019.5,20.3,14.2,68,0.8,10,2.4,240,0.0,0.0,0.0,0.65,...,...,...,2013-01-02
15,16,1019.0,1020.3,19.5,14.5,73,2.0,350,4.6,350,0.0,0.0,0.0,0.13,...,...,...,2013-01-02
16,17,1019.8,1021.1,18.7,14.6,77,1.3,340,3.9,350,0.0,0.0,0.0,0.00,12.0,...,9.0,2013-01-02
17,18,1020.5,1021.8,18.2,14.5,79,1.3,330,3.4,350,0.0,0.0,0.0,0.00,...,...,...,2013-01-02
18,19,1021.2,1022.5,18.2,14.7,80,0.4,30,2.7,330,0.0,0.0,0.0,0.00,...,...,...,2013-01-02
19,20,1021.5,1022.8,18.1,14.9,82,0.9,70,2.6,10,0.0,0.0,...,0.00,10.0,...,10.0,2013-01-02
20,21,1021.9,1023.2,17.5,15.1,86,0.4,60,2.0,60,0.5,0.5,...,0.00,8.0,...,10.0,2013-01-02
21,22,1022.2,1023.5,17.3,14.9,86,1.0,60,2.1,100,T,1.0,...,0.00,...,...,...,2013-01-02
22,23,1022.6,1023.9,16.5,14.3,87,0.3,20,2.5,90,3.0,1.0,...,0.00,6.0,...,10.0,2013-01-02
23,24,1023.1,1024.4,16.1,14.0,87,0.5,350,3.9,350,1.0,1.0,...,0.00,...,...,...,2013-01-02

In [26]:
cols = list(Data.columns)
cols = ['Date'] + cols[:-1]
Data = Data[cols]
Data

,Date,ObsTime,StnPres,SeaPres,Temperature,Td dew point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,SunShine,GloblRad,Visb,UVI,Cloud Amount
0,2013-01-02,1,1017.9,1019.2,14.5,12.5,88,2.0,30,4.3,90,T,1.0,...,0.00,...,...,...
1,2013-01-02,2,1017.8,1019.1,14.8,12.6,87,1.1,30,4.7,30,T,0.5,...,0.00,16.0,...,10.0
2,2013-01-02,3,1017.3,1018.6,14.9,12.5,86,1.1,20,2.8,10,0.0,0.0,...,0.00,...,...,...
3,2013-01-02,4,1017.2,1018.5,15.1,12.7,86,0.7,350,2.7,350,0.0,0.0,...,0.00,...,...,...
4,2013-01-02,5,1017.2,1018.5,14.5,12.6,88,0.1,0,1.8,340,0.0,0.0,...,0.00,15.0,...,10.0
5,2013-01-02,6,1018.1,1019.4,14.4,12.5,88,1.2,200,2.5,200,0.0,0.0,0.0,0.00,...,...,...
6,2013-01-02,7,1018.7,1020.0,14.4,12.5,88,0.9,190,2.7,210,0.0,0.0,0.0,0.00,...,...,...
7,2013-01-02,8,1019.3,1020.6,14.9,12.9,88,0.8,170,2.4,210,0.0,0.0,0.0,0.00,15.0,...,9.0
8,2013-01-02,9,1019.7,1021.0,16.2,13.4,83,0.1,0,1.9,210,0.0,0.0,0.1,0.51,15.0,...,9.0
9,2013-01-02,10,1020.2,1021.5,17.3,14.2,82,0.2,0,1.6,300,T,0.5,0.0,0.62,...,...,...
10,2013-01-02,11,1019.6,1020.9,18.9,14.8,77,0.8,250,2.3,260,0.0,0.0,0.4,1.51,13.0,...,8.0
11,2013-01-02,12,1019.4,1020.7,19.5,14.2,71,1.6,210,3.5,230,0.0,0.0,0.2,1.05,...,...,...
12,2013-01-02,13,1018.8,1020.1,19.3,14.1,72,0.8,200,2.5,200,0.0,0.0,0.0,0.30,...,...,...
13,2013-01-02,14,1018.2,1019.5,20.0,14.3,70,1.8,240,3.3,210,0.0,0.0,0.0,0.60,10.0,...,7.0
14,2013-01-02,15,1018.2,1019.5,20.3,14.2,68,0.8,10,2.4,240,0.0,0.0,0.0,0.65,...,...,...
15,2013-01-02,16,1019.0,1020.3,19.5,14.5,73,2.0,350,4.6,350,0.0,0.0,0.0,0.13,...,...,...
16,2013-01-02,17,1019.8,1021.1,18.7,14.6,77,1.3,340,3.9,350,0.0,0.0,0.0,0.00,12.0,...,9.0
17,2013-01-02,18,1020.5,1021.8,18.2,14.5,79,1.3,330,3.4,350,0.0,0.0,0.0,0.00,...,...,...
18,2013-01-02,19,1021.2,1022.5,18.2,14.7,80,0.4,30,2.7,330,0.0,0.0,0.0,0.00,...,...,...
19,2013-01-02,20,1021.5,1022.8,18.1,14.9,82,0.9,70,2.6,10,0.0,0.0,...,0.00,10.0,...,10.0
20,2013-01-02,21,1021.9,1023.2,17.5,15.1,86,0.4,60,2.0,60,0.5,0.5,...,0.00,8.0,...,10.0
21,2013-01-02,22,1022.2,1023.5,17.3,14.9,86,1.0,60,2.1,100,T,1.0,...,0.00,...,...,...
22,2013-01-02,23,1022.6,1023.9,16.5,14.3,87,0.3,20,2.5,90,3.0,1.0,...,0.00,6.0,...,10.0
23,2013-01-02,24,1023.1,1024.4,16.1,14.0,87,0.5,350,3.9,350,1.0,1.0,...,0.00,...,...,...

In [27]:
type(Data)

pandas.core.frame.DataFrame

In [30]:
data = pd.read_csv('./weather.csv')
date = data['whole_date']
data['whole_date'] = pd.to_datetime(data['whole_date'])
type(date.iloc[1])

C:\Users\student\AppData\Local\Temp\ipykernel_3880\107442236.py:1: DtypeWarning: Columns (3,4,5,6,7,8,10,11,13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./weather.csv')

str

In [33]:
from datetime import datetime, timedelta,date
start_time = pd.Timestamp('2017-01-01')
end_time = pd.Timestamp('2023-12-31')
filtered_data = data[(data['whole_date'] >= start_time) & (data['whole_date'] <= end_time)]
filtered_data

,Station_ID,whole_date,ObsTime,StnPres,SeaPres,Temperature,Td_dew_point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,SunShine,GloblRad,Visb,UVI,Cloud_Amount
34970,466880,2017-01-01,1,1021.4,1022.7,20.2,14.5,70,2.5,60,5.8,80,0,0,...,0,...,...,...
34971,466880,2017-01-01,2,1020.7,1022,20.3,14.4,69,3.7,60,6.5,50,0,0,...,0,20,...,1
34972,466880,2017-01-01,3,1020.2,1021.5,20.5,14.5,68,3.7,60,8.1,50,0,0,...,0,...,...,...
34973,466880,2017-01-01,4,1019.9,1021.2,20.4,14.5,69,3.8,70,7.5,30,0,0,...,0,...,...,...
34974,466880,2017-01-01,5,1020.2,1021.5,20.2,14.5,70,4,70,7.2,40,0,0,...,0,20,...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182085,466920,2023-05-23,20,1009.8,1013.4,21.9,16.9,73,2.5,100,6.1,80,0,0,...,0,...,0,...
182086,466920,2023-05-23,21,1009.7,1013.3,21.7,16.9,74,2.5,120,6.4,120,0,0,...,0,...,0,...
182087,466920,2023-05-23,22,1009.9,1013.5,21.7,16.9,74,2.2,100,7.1,130,0,0,...,0,...,0,...
182088,466920,2023-05-23,23,1009.6,1013.2,21.7,16.7,73,3.2,90,7.9,80,0,0,...,0,...,0,...
182089,466920,2023-05-23,24,1008.7,1012.3,21.5,16.9,75,3.1,90,8.2,80,0,0,...,0,...,0,...